filter:
    paths:
        - application/controllers/*
        - application/core/*
        - application/database/*
        - application/helpers/*
        - application/hooks/*
        - application/libraries/*
        - application/models/*
        - application/views/*
